DROP TABLE IF EXISTS sensors;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS triggers;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS statechanges;

CREATE TABLE sensors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL
);

CREATE TABLE states (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL
);

CREATE TABLE triggers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL
);

CREATE TABLE measurements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sensor_id INTEGER NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value FLOAT NOT NULL,
  FOREIGN KEY (sensor_id) REFERENCES sensors (id)
);

CREATE TABLE statechanges (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  old_state INTEGER NOT NULL,
  new_state INTEGER NOT NULL,
  cause INTEGER NOT NULL,
  FOREIGN KEY (old_state) REFERENCES states (id),
  FOREIGN KEY (new_state) REFERENCES states (id),
  FOREIGN KEY (cause) REFERENCES triggers (id)
);


